namespace Bottom_botV2.Utils
{
    class Constants
    {
        public static int kMessagesToTrigger = 50;
        public static string kBotPrefix = "!";
        public static string[] kListSmashCharacters = {
            "Bayonetta",
            "Bowser",
            "Bowser Jr.",
            "Byleth",
            "Captain Falcon",
            "Chrom",
            "Cloud",
            "Corrin",
            "Daisy",
            "Dark Pit",
            "Dark Samus",
            "Diddy Kong",
            "Donkey Kong",
            "Dr Mario",
            "Duck Hunt Duo",
            "Falco",
            "Fox",
            "Ganondorf",
            "Greninja",
            "Hero",
            "Ice Climbers",
            "Ike",
            "Incineroar",
            "Inkling",
            "Isabelle",
            "Jigglypuff",
            "Joker",
            "Ken",
            "King Dedede",
            "King K. Rool",
            "Kirby",
            "Link",
            "Little Mac",
            "Lucario",
            "Lucas",
            "Lucina",
            "Luigi",
            "Mario",
            "Marth",
            "Mega Man",
            "Meta Knight",
            "Mewtwo",
            "Mii Brawler",
            "Mii Gunner",
            "Mii Swordfighter",
            "Min Min",
            "Mr Game and Watch",
            "Ness",
            "Olimar",
            "Pac-Man",
            "Palutena",
            "Peach",
            "Piranha Plant",
            "Pichu",
            "Pikachu",
            "Pit",
            "Pokemon Trainer",
            "R.O.B",
            "Richter",
            "Ridley",
            "Robin",
            "Rosalina and Luma",
            "Roy",
            "Ryu",
            "Samus",
            "Sephiroth",
            "Sheik",
            "Shulk",
            "Simon",
            "Snake",
            "Sonic",
            "Steve",
            "Terry",
            "Toon Link",
            "Villager",
            "Wario",
            "Wii Fit Trainer",
            "Wolf",
            "Yoshi",
            "Young Link",
            "Zelda",
            "Zero Suit Samus",
        };
        public static string[] kListResponseMessages = {
            "RNG RNG RNG",
            "He he balanceado",
            "Por que *CHAR* é tão divertido(a)?!?",
            "Por que *CHAR* é tão roubado(a)?!?",
            "\"ACTUALLY\"",
            "Not gonna lie, meu/minha *CHAR* ta kinda schnasty",
            "Aff, fui pro meme",
            "Cala a boca *USER*, seu/sua *CHAR* ta cansado(a)",
            "Mano, Min Min não deveria ter entrado no jogo, olha esse boneco",
            "OLHA ESSA RANGE",
            "*CHAR* tem umas microfalhas",
            "DEIXA EU FALAR DEIXA EU FALAR",
            "Bora Smash *USER*?",
            "Meu PT é ruim :(",
            "Eu não sou horny :(",
            "Esse golpe do(a) *CHAR* é quebrado",
            "Esse golpe do(a) *CHAR* não funciona",
            "Cansei do PT, agora to de *CHAR*"
        };
    }
}
